import type { Metadata } from "next";
import localFont from "next/font/local";
import "@/styles/globals.css";
import MainLayout from "@/interfaces/layouts/main_layout";
import { ProviderReduxToolkit } from "@/modules/providers/redux_provider";
import ProviderTheme from "@/modules/providers/theme_provider";
import { Color } from "@/styles/color";
import NextTopLoader from "nextjs-toploader";

const geistSans = localFont({
	src: "./fonts/GeistVF.woff",
	variable: "--font-geist-sans",
	weight: "100 900",
});
const geistMono = localFont({
	src: "./fonts/GeistMonoVF.woff",
	variable: "--font-geist-mono",
	weight: "100 900",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<ProviderReduxToolkit>
					<ProviderTheme>
						<MainLayout>
							<NextTopLoader height={2} color={Color.Main.Base} />
							<main>{children}</main>
						</MainLayout>
					</ProviderTheme>
				</ProviderReduxToolkit>
			</body>
		</html>
	);
}
